name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Validate Gradle Wrapper
        run: ./gradlew --version
      - name: Run Tests
        run: ./gradlew test
      - name: Create coverage-data directory and copy contents
        run: |
          mkdir -p .qodana/code-coverage
          cp -R build/reports/jacoco/test/* .qodana/code-coverage/
      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: gradle-coverage-data-jacoco
          path: .qodana/code-coverage
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1149245604 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'